### ISSUE TITLE
About display driver, pure python or hybrid.

### ISSUE THREAD

**Issue by sam0910** [kdschlosser/lvgl_micropython#19]
Greetings!

Always thanks to @kdschlosser for maintaining this great project.
you are the savior of micropython bindings.

I found a LVGL blog about [Display driver, pure python or hybrid](https://blog.lvgl.io/2019-08-05/micropython-pure-display-driver#pure-micropython-driver)
[lvgl/lv_micropython_biding](https://github.com/lvgl/lv_binding_micropython/blob/dc5bb8fcf183c532c1bfa789e0a4bd364a68c3e3/driver/esp32/ili9XXX.py) is still using C callback for ili9341, ili9488, ili9488g, gc9a01, st7789 for the performance.

I know you are busy on many other great things and also this repo is on going,
Could I ask, is there a plan to use C callback or viper emitter?

Great thanks again.

**Comment by kdschlosser** [comment]
The reason why with the current official binding there is a "pure python" or "hybrid" is because of how the official binding deals with flushing the frame buffer and the copying of the frame buffer data. In my version of the binding I have eliminated the need to copy anything. The only thing that can take a bit of time to do is swapping the 2 bytes for each pixel when using RGB565. This is not something that has to be done for all displays and it is an option that can be turned on and off when constructing the display driver. 

I am guessing you are using the ESP32. and when working with the ESP32 the official binding exposes parts of the ESP32 SDK so it can be accessed from MicroPython. There are 2 components when working with a display, you have the chip that controls the display itself and you have the connection method to that chip. That connection method is what we call a "bus" which is short for data bus. The way the MCU connects to the display is going to be a standardized for of communication it will be SPI or i8080 or an RGB connection. These are the methods that the ESP32 is able to use. There are others but they are not supported by the ESP32.

Because the bus is standardized that means it is always go to work the same no matter what brand of display you use. The chip that controls the display is going to be different depending on what display you are using. In the official binding the bus and the code for the control chip are all put together. There is a problem with doing that. A single chip can support more than one connection type. it can support SPI , I8080 and RGB and depending on how it is connected to the ESP32 any of those can be used to communicate with the display.

What I did was I separated the bus from the display chip code. They are 2 separate things. The code for the bus is written in C code where as the code for the display IC is written in Python. The bus is what does the sending of the data and it need to be in C code for performance purposes. I came up with an API for the different busses that allow any display IC driver to work with any bus driver. This is because the function names to do things are the same and the data that gets passed to those functions is also the same. The display IC driver shouldn't need to have any knowledge and it shouldn't even care what bus is being used. That is how I wrote the code.

There is no reason to use the viper code emitter because anything that is written that needs to have speed is written in C code. The only thing the display IC driver does is pass the initial startup commands to the display which is a one shot and done thing so it only happens on startup. The other thing the display driver does is it acts as a go between when data is being passed from LVGL to the display. There is nothing that needs to be done during that process other than sending a memory address to the display before sending the frame buffer data to the display. The code in the display IC driver which is written in python simply passes the commands to the bus driver which is written in C. so once again the speed is at C code speed so no need for using the viper code emitter because it's not going to increase performance at all. It will end up using more memory.

This is the code that is used to handle passing the data from LVGL to the display. I will mark what is happening in the code for you to understand a little better.

```python
    def _flush_cb(self, _, area, color_p):
        # this is a simple math and is not CPU intensive
        # some displays have bezel around them and that bezel might 
        # overlap a little bit of the display. This allows us to shift the data
        # so it is not under the bezel.
        x1 = area.x1 + self._offset_x
        x2 = area.x2 + self._offset_x

        y1 = area.y1 + self._offset_y
        y2 = area.y2 + self._offset_y

        # This is how the original binding was set up and I have not 
        # changed this portion. It will be something that I will change
        # in the future because it is a step that really doesn't need to take place
        # The sole purpose of this is to convert the buffer data into a memory view object
        # so we can pass it to the bus driver to be transmitted
        size = (
            (x2 - x1 + 1) *
            (y2 - y1 + 1) *
            lv.color_format_get_size(self._color_space)
        )
       
       # I separated sending any commands to the display when flushing the frame buffer because 
       # I didn't want to have to repeat code for flushing the frame buffer.  Some displays 
       # you don't have to send any commands to when flushing the frame buffer and that is able to be
       # done without having to rewrite the code in this function. 
       cmd = self._set_memory_location(x1, y1, x2, y2)

        # we have to use the __dereference__ method because this method is
        # what converts from the C_Array object the binding passes into a
        # memoryview object that can be passed to the bus drivers
        data_view = color_p.__dereference__(size)

        # This is the call where we pass the data to the display. The actual code that does this is written in C code.
        self._data_bus.tx_color(cmd, data_view, x1, y1, x2, y2)
```

if this function is put into the viper code emitter the only thing you are going to make faster is the math that is done. There really isn't all that much math being done int he flush function. There is always a cost when wanting to improve performance and with the viper code emitter that cost is memory. You use a lot more memory in order to increase speed. Memory is not one of those things that an MCU had a bucket load of. Because there is a very tiny amount of math in this function you would not see a large improvement in speed. We are talking a resolution measured in maybe nanoseconds. but the extra memory cost to gain a few nanoseconds doesn't make it worth doing.


This is the code in the original binding when using "hybrid" for flushing the buffer.

```


DMA_ATTR static uint8_t dma_buf[4] = {0};
DMA_ATTR static spi_transaction_t spi_trans = {0};

static void spi_send_value(const uint8_t *value, uint8_t size, spi_device_handle_t spi)
{
    spi_trans.length = size*8;
    spi_trans.tx_buffer = value;
    spi_trans.user = NULL;
    spi_device_polling_transmit(spi, &spi_trans);
}

static inline void ili9xxx_send_cmd(uint8_t cmd, int dc, spi_device_handle_t spi)
{
   dma_buf[0] = cmd;
   gpio_set_level(dc, 0);
   spi_send_value(dma_buf, 1, spi);
}

static inline void ili9xxx_send_data(const uint8_t *value, int dc, spi_device_handle_t spi)
{
   gpio_set_level(dc, 1);
   spi_send_value(value, 4, spi);
}

static void ili9xxx_send_data_dma(void *disp_drv, void *data, size_t size, int dc, spi_device_handle_t spi)
{
    gpio_set_level(dc, 1);
    spi_trans.length = size*8;
    spi_trans.tx_buffer = data;
    spi_trans.user = disp_drv;
    spi_device_queue_trans(spi, &spi_trans, -1);
}

void ili9xxx_flush(void *_disp_drv, const void *_area, void *_color_p)
{
    lv_display_t *disp_drv = _disp_drv;
    const lv_area_t *area = _area;
    lv_color_t *color_p = _color_p;
    int start_x = 0;
    int start_y = 0;

    void *driver_data = lv_display_get_driver_data(disp_drv);

    // We use disp_drv->driver_data to pass data from MP to C
    // The following lines extract dc and spi

    int dc = mp_obj_get_int(mp_obj_dict_get(driver_data, MP_OBJ_NEW_QSTR(MP_QSTR_dc)));
    int dt = mp_obj_get_int(mp_obj_dict_get(driver_data, MP_OBJ_NEW_QSTR(MP_QSTR_dt)));
    mp_buffer_info_t buffer_info;
    mp_get_buffer_raise(mp_obj_dict_get(driver_data, MP_OBJ_NEW_QSTR(MP_QSTR_spi)), &buffer_info, MP_BUFFER_READ);
    spi_device_handle_t *spi_ptr = buffer_info.buf;

    // Some devices may need a start_x and start_y offset for displays with LCD screens smaller
    // than the devices built in frame buffer.

    start_x = mp_obj_get_int(mp_obj_dict_get(driver_data, MP_OBJ_NEW_QSTR(MP_QSTR_start_x)));
    start_y = mp_obj_get_int(mp_obj_dict_get(driver_data, MP_OBJ_NEW_QSTR(MP_QSTR_start_y)));

    int x1 = area->x1 + start_x;
    int x2 = area->x2 + start_x;
    int y1 = area->y1 + start_y;
    int y2 = area->y2 + start_y;

    // Column addresses

    ili9xxx_send_cmd(0x2A, dc, *spi_ptr);
    dma_buf[0] = (x1 >> 8) & 0xFF;
    dma_buf[1] = x1 & 0xFF;
    dma_buf[2] = (x2 >> 8) & 0xFF;
    dma_buf[3] = x2 & 0xFF;

    ili9xxx_send_data(dma_buf, dc, *spi_ptr);

    // Page addresses

    ili9xxx_send_cmd(0x2B, dc, *spi_ptr);
    dma_buf[0] = (y1 >> 8) & 0xFF;
    dma_buf[1] = y1 & 0xFF;
    dma_buf[2] = (y2 >> 8) & 0xFF;
    dma_buf[3] = y2 & 0xFF;

    ili9xxx_send_data(dma_buf, dc, *spi_ptr);

    // Memory write by DMA, disp_flush_ready when finished

    ili9xxx_send_cmd(0x2C, dc, *spi_ptr);

    size_t size = (area->x2 - area->x1 + 1) * (area->y2 - area->y1 + 1);
    uint8_t color_size = 2;

    bool swap_rgb565_bytes = mp_obj_get_int(mp_obj_dict_get(driver_data, MP_OBJ_NEW_QSTR(MP_QSTR_swap_rgb565_bytes)));
    if ( swap_rgb565_bytes == true ) {
        lv_draw_sw_rgb565_swap(color_p, size);
    }

    if ( dt == DISPLAY_TYPE_ILI9488 ) {
        color_size = 3;
        /*Convert ARGB to RGB is required (cut off A-byte)*/
        size_t i;
        lv_color32_t* tmp32 = (lv_color32_t*) color_p;
        color24_t* tmp24 = (color24_t*) color_p;

        for(i=0; i < size; i++) {
            tmp24[i].red = tmp32[i].red;
            tmp24[i].green = tmp32[i].green;
            tmp24[i].blue = tmp32[i].blue;
        }
    }

    ili9xxx_send_data_dma(disp_drv, color_p, size * color_size, dc, *spi_ptr);
}
```

and this is all of the code C and Python that is used to flush the buffer in the binding I wrote

```python

    def _set_memory_location(self, x1, y1, x2, y2):
        # Column addresses
        param_buf = self._param_buf  # NOQA

        param_buf[0] = (x1 >> 8) & 0xFF
        param_buf[1] = x1 & 0xFF
        param_buf[2] = (x2 >> 8) & 0xFF
        param_buf[3] = x2 & 0xFF

        self._data_bus.tx_param(_CASET, self._param_mv)

        # Page addresses
        param_buf[0] = (y1 >> 8) & 0xFF
        param_buf[1] = y1 & 0xFF
        param_buf[2] = (y2 >> 8) & 0xFF
        param_buf[3] = y2 & 0xFF

        self._data_bus.tx_param(_RASET, self._param_mv)

        return _RAMWR

    def _flush_cb(self, _, area, color_p):
        x1 = area.x1 + self._offset_x
        x2 = area.x2 + self._offset_x

        y1 = area.y1 + self._offset_y
        y2 = area.y2 + self._offset_y

        size = (
            (x2 - x1 + 1) *
            (y2 - y1 + 1) *
            lv.color_format_get_size(self._color_space)
        )

        cmd = self._set_memory_location(x1, y1, x2, y2)

        # we have to use the __dereference__ method because this method is
        # what converts from the C_Array object the binding passes into a
        # memoryview object that can be passed to the bus drivers
        data_view = color_p.__dereference__(size)
        self._data_bus.tx_color(cmd, data_view, x1, y1, x2, y2)
```

```c
mp_lcd_err_t lcd_panel_io_tx_color(mp_obj_t obj, int lcd_cmd, void *color, size_t color_size, int x_start, int y_start, int x_end, int y_end)
    {
        mp_lcd_bus_obj_t *self = (mp_lcd_bus_obj_t *)obj;

        if (self->rgb565_byte_swap) {
            rgb565_byte_swap((uint16_t *)color, (uint32_t)(color_size / 2));
        }
       return esp_lcd_panel_io_tx_color(self->panel_io_handle.panel_io, lcd_cmd, color, color_size);
    }
```


Which do you think is going to be faster? Which is going to use less memory?

The biggest benifit to how I write the binding is LVGL is not a dependency of MicroPython. It is the other way around. By having it the other way around it allows me to change the MicroPython version that is being used simply by pulling the most recent code from the MicroPython repository.  It's not so simple with the official binding because compiling LVGL into MicroPython is nested into the MicroPython build system where my binding has it's own build system that gets run when compiling MicroPython. they are independent of each other. The other issue is the original binding needs to have access to LVGL in the C code for writing data to a display.  Changes made in LVGL can cause problems and the code to send the data to the display will need to be updated. Since there is no knowledge of LVGL in the binding I wrote when sending data to the display I will never have to alter the code at all when LVGL gets updated. What that means is when I want to update to a new LVGL version all I have to do is pull the new code in from the LVGL repository and maybe make a few small changes in the display drivers written in Python if there is an API naming change. I don't have to worry about large modifications in order to get it to work.

**Comment by sam0910** [comment]
Thank you for the detail reply, 
That is indeed a superior approach, I am amazed that you've done.

Great thanks indeed!
