### ISSUE TITLE
question about api_driver

### ISSUE THREAD

**Issue by chieve-bale** [kdschlosser/lvgl_micropython#87]
Thanks for your effort.
may you help me?
i want to know what difference between `/api_drivers/py_api_drivers` and `lvgl_api_drivers` ?

**Comment by kdschlosser** [comment]
The only thing being used at this point in time is the py_api_drivers. 

I had started working on flattening the API for LVGL in MicroPython so it would be identical to the C API. I have not yet finished working on it because other things had taken priority. I will get back to working on it at some point just don't know when. Since the API will be different there would need to be a different set of framework source files and that is what the lvgl_api_drivers contains.
